api/urls.py
from django.conf.urls import include
from django.urls import path

app_name='api'

urlpatterns = [
    path('ws/v1/', include('api.v1.urls', namespace="v1"))
]

core/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static
import core.views as views
from django.conf.urls import  include
from django.contrib import admin

app_name = "core"

urlpatterns = [
    path('', views.index, name='index'),
    path('admin', admin.site.urls, name='admin'),
    path('<str:categoria>', views.index, name='index'),
    path('receitas/nova/', views.nova_receita, name='nova_receita'),
    path('receitas/detalhes/<int:pk>/', views.detalhes_receita, name='detalhes_receita'),
    path('receitas/detalhes/<int:pk>/<str:fav>/', views.detalhes_receita, name='favoritar'),
    path('favoritos/', views.favoritos, name='favoritos')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

receitas/users/urls.py
from django.urls import path

from receitas.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

receitas/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
from django.contrib.auth.models import Group


class User(AbstractUser):
    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

    @classmethod
    def post_create(cls, sender, instance, created, *args, **kwargs):
        if not created:
            return
        instance.is_staff = True
        Group.objects.get(name='NormalUser').user_set.add(instance)
        instance.save()

post_save.connect(User.post_create, sender=User)

receitas/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

receitas/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

receitas/templates/pages/about.html
{% extends "base.html" %}

receitas/templates/pages/detalhes_receita.html
{% extends "base.html" %}
{% load static i18n %}

{% block content %}
<div class="container">
    <div class="row align-items-start">
        <div class="col">
            <div style="display: flex; justify-content: space-between;  align-items: center;padding-right: 10%;">
                <div>
                    <h3>
                        {{ receita.titulo }} - 
                        {% if receita.autor.name != "" %}
                        {{ receita.autor.name }}
                        {% else %}
                        {{ receita.autor.username }}
                        {% endif %}
                    </h3>
                    <div>
                    Preparo: <strong>{{ receita.tempo }}</strong> 
                    Avaliação: <strong>{{ receita.avaliacao }}</strong>
                </div>
            </div>
            <div class="remove-print" style="display: flex; justify-content: space-between; align-items: center; width: 25%;">
                <i class="fas fa-print" onclick="print()" style="cursor:pointer;font-size: 30px; text-align: center; color:#007bff;"></i>
                {% if favorito %}
                <a label="Favoritar" class="favorite fa fa-star" style="cursor:pointer;font-size: 30px; text-align: center; color:#007bff;" href="{% url 'core:favoritar' pk=receita.id fav='remover' %}" action="post">
                </a>
                {% else %}
                <a label="Favoritar" class="favorite far fa-star" style="cursor:pointer;font-size: 30px; text-align: center; color:#007bff;" href="{% if request.user.is_authenticated %}{% url 'core:favoritar' pk=receita.id fav='adicionar' %}
                {% else %}{% url 'account_login' %} {% endif %}">
                </a> 
                {% endif %}
                {% if request.user %}
                    <a class="btn btn-outline-primary" style="cursor:pointer;" id="btn_avaliar" data-toggle="modal" data-target="#exampleModal"> Avaliar </a>
                {% endif %}
                {% if request.user == receita.autor %}
                    <a class="btn btn-outline-primary" href="{% url 'admin:index' %}core/receita/{{ receita.id }}"> Editar </a>
                {% endif %}
            </div>
            </div>
            <div>
                    {% for cat in receita.categoria.all %}
                    <a href="{% url 'core:index' categoria=cat.slug %}"><button type="button" class="btn btn-outline-info">{{ cat }}</button></a>
                    {% endfor %}
            </div>
            <img class="img-thumbnail" style="margin: 1% 8%; width: 70%; height:40%;" src="{% get_media_prefix %}{{receita.imagem}}"/>
            <div>{{ receita.descricao|safe }}</div>

        </div>
    </div>
</div>

<!-- Comment Area -->
<div class="row bootstrap snippets remove-print">
    <div class="col-md-12 col-md-offset-2 col-sm-12">
        <div class="comment-wrapper">
            <div class="panel panel-info">
                <div class="panel-heading">
                    Comentários.
                </div>
                <div class="panel-body">
                    <form action="{% url 'core:detalhes_receita' pk=receita.id %}" method="POST">
                    {% csrf_token %}
                    <textarea class="form-control" name="comentario" placeholder="escreva um comentário..." rows="3"></textarea>
                    <br>
                    {% if request.user.is_authenticated %}
                    <button class="btn btn-info pull-right">Adicionar Comentário</button>
                    </form>
                    {% else %}
                    <div>Faça Login Para Comentar</div>
                    {% endif %}
                    <hr>
                    {% if comentarios %}
                        <ul class="media-list">
                            {% for  comentario in comentarios %}
                                <li class="media">
                                    <div class="media-body">
                                        <strong class="text-success">{{ comentario.autor.username }}</strong>
                                        <div style="display: flex; justify-content: space-between;">
                                            <p>
                                                {{ comentario.mensagem }}
                                            </p>
                                            {% if request.user == comentario.autor %}
                                            <a class="btn btn-outline-primary" style="cursor:pointer;" id="btn_remover" data-id={{ comentario.id }}> Remover </a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    {% else %}
                    <div style="padding: 30px;">Sem comentários, seja o primeiro!!</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Comment Area -->

<!-- End Area -->
<a style="padding: 3% 0;" href="{% url 'core:nova_receita' %}"><button class="btn btn-primary pull-right remove-print" style="width: 100%;">Adicione sua Receita!!!!</button></a>

<!-- Modal Area -->
<div id='myModal' class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" style="text-align: center;">
        {% if nota_user %}
        <p>Caso queira alterar sua nota clique em Enviar.</p>
        <input id="valor_nota" value={{ nota_user.rating }}  min="1" max="5" type="number" onkeyup="if(this.value > 5) this.value = null;this.value=this.value.replace(/[^\d]/,'');"/>
        {% else %}
        <p>De uma nota de 1 a 5 para a receita!</p>
          <input id="valor_nota" value='1'  min="1" max="5" type="number" onkeyup="if(this.value > 5) this.value = null;this.value=this.value.replace(/[^\d]/,'');"/>
        {% endif %}
        </div>
        <div class="modal-footer">
          <button id="enviar_nota" type="button" class="btn btn-primary">Enviar</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
</div>
<!-- End Modal Area -->
{% endblock content %}
{% block extra_js %}
<script>
$(document).ready(function() {
    var URL_AVALIACAO = "{{ request.get_host }}" + '/ws/v1/avaliacoes/';
    var URL_COMENTARIO = "{{ request.get_host }}" + '/ws/v1/comentarios/';
    var RECEITA_ID = "{{ receita.id  }}";
    var RATING_NOTA = "{{ nota_user.rating }}"
    var ID_NOTA = "{{ nota_user.id }}"


    $('#btn_avaliar').click(function() {
        $('#myModal').modal('show');
    })

    $('#myModal').on('shown.bs.modal', function () {

       $('#enviar_nota').on('click', function(){
        /*
        Funcao responsavel por avaliar a receita
        */
        var valor_nota = $('#valor_nota').val();
        var data = JSON.stringify({
            'receita': '{{ receita.id }}',
            'rating': valor_nota
        });
        var url = 'http://' + URL_AVALIACAO;
        if(ID_NOTA){
            type = 'PATCH';
            data.id = ID_NOTA;
            url += ID_NOTA + '/';
        }else {
            type = 'POST';
        }
        $.ajax(
            {
                type: type,
                url: url,
                contentType: 'application/json',
                dataType: "json",
                data: data,
                beforeSend: function (xhr, settings) {
                    xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
                },
                success: function(response) {
                console.log(response);
                $('#myModal').modal('hide');
                },
                error: function (xhr, textStatus, errorThrown) {
                console.log(xhr, textStatus, errorThrown);
                }
            }
        );
    });
    });

    $(document).on('click', '#btn_remover', function(e){
        e.preventDefault();
        var el = $(this);
        comentario_id = el.attr('data-id');
        url = 'http://' + URL_COMENTARIO + comentario_id + '/';
        $.ajax(
                {
                    type: 'DELETE',
                    url: url,
                    contentType: 'application/json',
                    dataType: "json",
                    data: {},
                    beforeSend: function (xhr, settings) {
                        xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
                    },
                    success: function(response) {
                        el.closest('li').remove();
                    },
                    error: function (xhr, textStatus, errorThrown) {
                    console.log(xhr, textStatus, errorThrown);
                    }
                }
        );
    })
});
</script>

{% endblock extra_js %}

receitas/templates/pages/favoritos.html
{% extends "base.html" %}

{% block content %}
    <ul class="list-group"></ul>
        {% for favorito in favoritos %}
        <li style="display: flex; justify-content: space-between; align-items: center; width: 50%; "class="list-group-item">
            <p >{{ favorito.receita.titulo }} - {{ favorito.receita.avaliacao }}</p>
            <a class="btn btn-outline-primary" style="cursor:pointer;" id="btn_remover" data-id={{ favorito.id }}> Remover </a>
        </li>
        {% endfor %}
    </ul>
{% endblock content %}



{% block extra_js %}
<script>
$(document).ready(function() {
    var URL_AVALIACAO = "http://{{ request.get_host }}" + '/ws/v1/favoritos/';



    $(document).on('click', '#btn_remover', function(e){
    e.preventDefault();
    var el = $(this);
    favorite_id = el.attr('data-id');
    $.ajax(
            {
                type: 'DELETE',
                url: URL_AVALIACAO + favorite_id + '/',
                contentType: 'application/json',
                dataType: "json",
                data: {},
                beforeSend: function (xhr, settings) {
                    xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
                },
                success: function(response) {
                    el.closest('li').remove();
                },
                error: function (xhr, textStatus, errorThrown) {
                console.log(xhr, textStatus, errorThrown);
                }
            }
    );
});

});
</script>
{% endblock extra_js %}

receitas/templates/pages/home.html
{% extends "base.html" %}
{% load static i18n %}

{% block content %}

<div style="padding-top: 10px;">
{% if not selecionada %}
<a style="margin-right: 3px;" href="{% url 'core:index' %}"><button type="button" class="btn btn-info">Todas</button></a>
{% else %}
<a style="margin-right: 3px;" href="{% url 'core:index' %}"><button type="button" class="btn btn-outline-info">Todas</button></a>
{% endif %}
{% for categoria in categorias %}
    {% if categoria.slug == selecionada %} 
    <a style="margin-right: 3px;" href="{% url 'core:index' categoria=categoria.slug %}"><button type="button" class="btn btn-info">{{ categoria }}</button></a>
    {% else %}
    <a style="margin-right: 3px;" href="{% url 'core:index' categoria=categoria.slug %}"><button type="button" class="btn btn-outline-info ">{{ categoria }}</button></a>
    {% endif %}
{% endfor %}
</div>

<h3 style="text-align: center;border-bottom: 6px solid #4dd4; margin: 25px 0; padding: 10px 0;">Receitas</h3>
<div class="container">
        <div class="row align-items-start">
                {% if not receitas %}
                <div class="container h-100 d-flex justify-content-center">
                        <div class="jumbotron">
                          <h4 class="display-12">Não há receitas para essa categoria</h4>
                        </div>
                    </div>
                {% endif %}
        {% for receita in receitas %}
        <div class="col-md-6">
            <div style="display: flex;justify-content: space-between;">
                <p>
                    <strong>{{ receita.titulo }}</strong> - 
                    por 
                    {% if receita.autor.name != "" %}
                        {{ receita.autor.name }} {{ receita.autor.lastname }}
                    {% else %}
                        {{ receita.autor.username }}
                    {% endif %}
                </p>
            </div>
                <div style="display: flex;justify-content: space-between;">
                    <p>
                        Preparo: <strong>{{ receita.tempo }}</strong>
                    </p>
                    <p>
                    Avaliação: <strong>{{ receita.avaliacao }}</strong>
                    </p>
                </div>
            <a href="{% url 'core:detalhes_receita' pk=receita.id  %}">
                    <img class="img-thumbnail" src="{% get_media_prefix %}{{receita.imagem}}"/>
            </a>
            {% for cat in receita.categoria.all %}
            <p class="btn btn-outline-info ">{{ cat }}</p>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</div>
<a style="padding: 5% 0;" href="{% url 'core:nova_receita' %}"><button class="btn btn-primary pull-right" style="width: 100%;">Adicione sua Receita!!!!</button></a>

{% endblock content %}

receitas/templates/pages/nova_receita.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content" style="width: 75%;">
<form action="{% url 'core:nova_receita' %}" method="POST" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary pull-right">Post</button>
</form>
</div>
<script>
//Remocao campo descricao para o iframe do summernote sobrescrever
$( document ).ready(function() {
    $('.summernotewidget').removeClass('form-control');
});
</script>
{% endblock content %}